### ISSUE TITLE
Fix bug where DynamoDB cannot read from AWS profile other than default

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/spark-streaming-example-project#22]
```
at org.apache.spark.streaming.kinesis.KinesisReceiver.onStart(KinesisReceiver.scala:131)
at org.apache.spark.streaming.receiver.ReceiverSupervisor.startReceiver(ReceiverSupervisor.scala:125)
at org.apache.spark.streaming.receiver.ReceiverSupervisor.start(ReceiverSupervisor.scala:109)
at org.apache.spark.streaming.scheduler.ReceiverTracker$ReceiverLauncher$$anonfun$8.apply(ReceiverTracker.scala:308)
at org.apache.spark.streaming.scheduler.ReceiverTracker$ReceiverLauncher$$anonfun$8.apply(ReceiverTracker.scala:300)
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
at org.apache.spark.scheduler.Task.run(Task.scala:70)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:3228)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.createTable(AmazonDynamoDBClient.java:1047)
at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:117)
... 16 more
15/06/09 17:51:56 INFO JobScheduler: Starting job streaming job 1433872316000 ms.0 from job set of time 1433872316000 ms
15/06/09 17:51:56 INFO JobScheduler: Added jobs for time 1433872316000 ms
15/06/09 17:51:56 INFO SparkContext: Starting job: foreachRDD at StreamingCounts.scala:100
15/06/09 17:51:56 INFO DAGScheduler: Registering RDD 443 (map at StreamingCounts.scala:86)
15/06/09 17:51:56 INFO
```

**Comment by bigsnarfdude** [comment]
Could only resolve it with changing hocon and using "aws configure" command instead of "inv create_profile"

**Comment by alexanderdean** [comment]
Thanks for exploring this Vincent! I agree - let's go with your fix. I am renaming this ticket and pushing it back to 0.2.0
